
export const mockData = [
  {
    taskType: 5,
    title: 'Task 5',
    content: 'Describe a photo of yourself that you like (please say where the photo was taken and what you were doing)',
    preparationTime: 3,
    selectionTime: 3,
    recordingTime: 6,
    images: [
      'https://images.unsplash.com/photo-1696266262379-1f3b5cbaf114?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2788&q=80',
      'https://images.unsplash.com/photo-1597424482786-0b1b7065dbac?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2100&q=80',
      'https://plus.unsplash.com/premium_photo-1695239201433-989396348447?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2787&q=80'
    ],
    descs: ['1. select 1; 2. select 1', '1. select 2; 2. select 2.', '3. select 3; select 3'],
    audio: null,
  },
  {
    taskType: 3,
    title: 'Task 3',
    content: 'Describe a scene',
    preparationTime: 3,
    recordingTime: 10,
    image: process.env.PUBLIC_URL + '/assets/images/1.png',
    audio: null,
  },
  {
    taskType: 0,
    title: 'Practice Task',
    content: 'Tell me about your best friend',
    preparationTime: 3,
    recordingTime: 6,
  },
  {
    taskType: 1,
    title: 'Task 1',
    content: 'Giving advice',
    preparationTime: 3,
    recordingTime: 9,
    audio: null,
  },
  {
    taskType: 2,
    title: 'Task 2',
    content: 'Personal experiences',
    preparationTime: 3,
    recordingTime: 6,
    image: null,
    audio: null,
  },
  {
    taskType: 3,
    title: 'Task 3',
    content: 'Describe a scene',
    preparationTime: 3,
    recordingTime: 6,
    image:process.env.PUBLIC_URL + '/assets/images/1.png',
    audio: null,
  },
  {
    taskType: 4,
    title: 'Task 4',
    content: 'Make predictions',
    preparationTime: 3,
    recordingTime: 6,
    image:process.env.PUBLIC_URL + '/assets/images/1.png',
    audio: null,
  },
  {
      taskType: 6,
      title: 'Task 6',
      content: 'Difficult situation',
      preparationTime: 6,
      recordingTime: 6,
      images: [],
      descs: [],
      audio: null,
  },
  {
    taskType: 7,
    title: 'Task 7',
    content: 'Opinion',
    preparationTime: 3,
    recordingTime: 9,
    images: [],
    descs: [],
    audio: null,
  },
  {
    taskType: 8,
    title: 'Task 8',
    content: 'Unsual situation',
    preparationTime: 3,
    recordingTime: 6,
    image:process.env.PUBLIC_URL + '/assets/images/1.png',
    audio: null,
  },
]



